= Day1 Boot入門

= SpringBootとは？

https://github.com/Macchinetta/springboot-development-reference/blob/master/src/main/asciidoc/ja/SpringBoot_basics.adoc[Macchinetta - SpringBootの基本]
に大体書いてある。

https://spring.pleiades.io/spring-boot/docs/2.3.4.RELEASE/reference/html/getting-started.html#getting-started[公式 - はじめに]
もちらっと。

== それまでのSpringアプリケーション

=== Springの進化

https://www.slideshare.net/movmov/spring-12-49833796[Springの歴史]

1.0::
* EJB(特に2.0)死ね -> DIコンテナを提供。この、コンテナを手にできるというのが、超絶画期的。
* XML定義。すべて手動かつ冗長な記述。超絶地獄。
** TERA Batch 2.x をみるとツラさわかる
2.0::
* 機能拡充
* 簡略化記法
2.5::
* component-scan!!!
** アノテーションベース!!!でもXML!!!
3.0::
* Java-Config!!!
* JSR対応
4.0::
* Java8+!!!

=== Springアプリのツラミ

* 設定地獄
* ライブラリ組み合わせ地獄
* 公式なベスト・プラクティスがない

=== Javaアプリのツラミ

動かすまでがクソだるい。動かしたあとの維持もクソだるい。

* 設定クソだるい
* 環境作成クソだるい
* ビルドクソだるい

== Spring Boot がしたこと

ツラミを全部解消した。

* 設定はベスト・プラクティスが自動反映
* ライブラリもパスにあれば自動反映/勝手に調整
* 環境作成？シングルJarで動きますがなにか？(＝Boot-Jar)

ここまでやると更にできることがあるので、便利にした

* 開発ツール(Hot-Reloadとかそういうの)
* 運用機能(メトリクス/ヘルチェ)
* サーバ環境でのUT
* etc...

=== Bootiful???

Spring Boot を効果的に使ったAPのこと。 アドボケイト的なことをよくする Josh Long さん がよく言ってる印象。

=== 全てはバラ色か？

いいえ、そんなことはありません。

* 黒魔術感がすさまじい。
* Boot自体の開発スピードがあがったので油断するとすぐEOL。置いてきぼり。
* Boot-Jarの容量がパなぃ。

== コンテナフレンドリ

Dockerに入れやすい状態のアプリ。どうなっていれば入れやすい？ ちょっと考えてみましょう。

性質::
* AAA
* BBB
* CCC

様々なプログラミング言語の向き不向き？

* C
* Java
* Python
* JavaScript
* Go

では Bootアプリはコンテナフレンドリ？

== Hello Spring Boot !!!

https://spring.pleiades.io/guides/gs/rest-service/

== `@SpringBootApplication`?

こいつがマジで大事。

https://github.com/Macchinetta/springboot-development-reference/blob/master/src/main/asciidoc/ja/SpringBoot_architecture.adoc#11-sba%E3%82%92%E6%9C%89%E5%8A%B9%E3%81%AB%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AE%E8%A8%AD%E5%AE%9A[ココらへん]をもとに、意味を確認
