= Day3 Boot MVC

https://spring.pleiades.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-developing-web-applications[7. Web アプリケーションの開発]
がよくできているので、ココをベースに。

== RestAPIアプリを再確認

`hello` アプリを作ってみた。

== Embedded-Tomcatとは

https://tomcat.apache.org/tomcat-9.0-doc/api/org/apache/catalina/startup/Tomcat.html

Java API経由で Servletを追加して、startすることができる。

もともと、TomcatはPureJavaなServletコンテナで、プロダクト側が起動シーケンスを管理していた。
設定は web.xml のみが手段だった。

その後、 Servletの仕様が更新され、web.xmlは必須ではなくアノテーションによる記述が可能になるなど進化を続けた。

その過程で、テスト用として組み込みTomcatが提供され始め、商用でも当たり前のように使われるようになった。

== MVC周りで特に重要な部分(SpringMVC少なめ/Boot中心)

アーキテクチャは
http://terasolunaorg.github.io/guideline/5.6.0.RELEASE/ja/ArchitectureInDetail/WebServiceDetail/REST.html#restoverviewaboutrestfulwebservicedevelopment[TERA]
が解説してくれている。

=== MessageConverters

なにか知っていますか？

https://www.baeldung.com/spring-httpmessageconverter-rest[3rd party 記事] ですが…

カスタマイズする際は、Bean登録するだけというお手軽仕様です。

=== リクエストパス

誰が、パスマッチングしているんでしょう？

=== Error-Handling

==== RestControllerAdvice & ResponseEntityExceptionHandler 

Spring MVCの仕組み

https://qiita.com/shotana/items/f3627e45feb912946c7c

==== ErrorController

Spring Bootの仕組み

https://spring.pleiades.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-error-handling

==== 比較

https://qiita.com/haseesah/items/6b0f0fcfe681734e2617

== DBアクセス周り

=== DataSources

https://spring.pleiades.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-sql

データベースの設定も、ConfigurationProperties化されていて、application.propertiesで設定可能。

https://spring.pleiades.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#data-properties

`spring.datasource.dbcp2.*` を見ると分かる通り、大抵の設定はプロパティで可能。

また、ちょっとしたテクニックによって、2つのデータソースをつくったり、prefixを調整したりできる。

https://spring.pleiades.io/spring-boot/docs/current/reference/html/howto.html#howto-two-datasources

=== MyBatis Starter

メインコミッタが解説してくれているのでココを読めばわかる。

https://qiita.com/kazuki43zoo/items/ea79e206d7c2e990e478

* `mybatis-spring-boot-starter` をclasspathに含めれば準備OK
* MyBatisの設定は application.properties から `mybatis.configuration.*` で実施できます
* スキャンは自動
** `@MapperScan` アノテーションによって、特定のパッケージ配下をスキャンする
** `@SpringBootApplication` + `@org.apache.ibatis.annotations.Mapper` で Bootのスキャン対象と同じパッケージ配下、かつ、アノテーションついてるものだけをスキャンする。

